SDL サンプルの使い方を記載する
shiguredo/sora-cpp-sdk-samples pull request #5
Opened 2022-07-21 02:33 UTC by miosakuma

SDL サンプルの利用方法を記載しました。
https://github.com/shiguredo/sora-cpp-sdk-samples/blob/feature/doc-use/doc/USE_SDL_SAMPLE.md

ご意見、ご指摘もらえるとうれしいです。以下が書いていて迷った箇所です。

- ビルド手順は別ページにした方がよいか
- Ubuntu 系に Github Actions には含まれていない `pkg-config` を入れたが人の環境それぞれなので不要かもしれない

2022-07-21 02:52 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +#### Windows で Windows 版をビルドする
「Windows で Windows 版をビルドする」だと少しくどい気がするので
「Windows 向けのビルドをする」くらいで良い気がしますがどうでしょうか。
他のプラットフォームについても同様です。

2022-07-21 02:52 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 20.04 でUbuntu 20.04 (armv8) Jetson 版をビルドする
ここは「Ubuntu 20.04 でUbuntu 20.04 (armv8) Jetson  向けのビルドをする」で良いと思います

2022-07-21 02:52 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +multistrap に insecure なリポジトリからの取得を許可する設定をします
`sudo sed -e 's/Apt::Get::AllowUnauthentic～` も書くのであれば
` sudo apt install multistrap binutils-aarch64-linux-gnu`もあったほうが親切そうです

補足説明だけしてビルドコマンドだけ書いておしまいにしても良いのではないかと思いました。
例：multistrap に insecure なリポジトリからの取得を許可する設定が必要です。

2022-07-21 02:52 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +
`sudo apt install libdrm-dev` についても記載があったほうがよさそうです。

2022-07-21 03:27 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +
Github Actions を見て不要と判断しました。 CMakeLists も見ましたが Jetson 向けはなくても大丈夫そうです。

https://github.com/shiguredo/sora-cpp-sdk-samples/blob/develop/sdl_sample/ubuntu-20.04_x86_64/CMakeLists.txt#L28
https://github.com/shiguredo/sora-cpp-sdk-samples/blob/develop/sdl_sample/ubuntu-20.04_armv8_jetson/CMakeLists.txt#L28

2022-07-21 03:40 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +#### Windows で Windows 版をビルドする
ありがとうございます。指摘の通りに修正をしました。

2022-07-21 03:40 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 20.04 でUbuntu 20.04 (armv8) Jetson 版をビルドする
ありがとうございます。コメントいただいた内容の方がよいため修正をしました。

2022-07-21 03:46 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 20.04 向けのビルドをする
x86_64 と arm64v8 は明確にするようにしてほしい。

2022-07-21 03:46 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +#### Mac 向けのビルドをする
"macOS arm64 向けのビルド"

2022-07-21 03:47 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 22.04 向けのビルドをする
x86_64 を明記する

2022-07-21 03:47 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 20.04 で Ubuntu 20.04 (armv8) Jetson 向けのビルドをする
タイトルで x86_64 を省略しない。

2022-07-21 03:48 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +multistrap に insecure なリポジトリからの取得を許可する設定をします
👍

2022-07-21 03:48 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +multistrap に insecure なリポジトリからの取得を許可する設定をします
インストールコマンドを書くとするならば python3 も含めて以下になると思うのですが、利用する方の環境がそれぞれ違うのでインストールは各自の判断でやってもらおうと考えました。
`sudo apt install python3 multistrap binutils-aarch64-linux-gnu`

`sudo sed -e 's/Apt::Get::AllowUnauthentic～ ` を記載したのは文字による説明だけでなくコマンドが必要だと考えたためです。

2022-07-21 03:48 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +以下は Sora サーバのシグナリング URL `wss://sora.example.com` の `sora` チャンネルに `sendrecv` で接続する例です。
Sora は必ずシグナリング URL の PATH が /signaling なの wss://example.com/signaling と書くように統一する。

2022-07-21 03:49 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +```
```console として $ 始まりにしたほうが親切かも。

2022-07-21 03:50 UTC, voluntas commented on README.md
> +- Ubuntu 22.04 x86_64 以降
以降ではないので消してよさそう。

2022-07-21 03:50 UTC, voluntas commented on README.md
> +- macOS 12.4 M1 以降
M1 ではなく arm64 or Apple Silicon のほうが良さそう。M2 でるし。

2022-07-21 03:51 UTC, voluntas commented on README.md
> +- Ubuntu 20.04 x86_64 以降
こちらも以降の意味がないので消してよさそう

2022-07-21 03:52 UTC, voluntas commented on README.md
> +Sora と映像の送受信を行い、SDL (Simple DirectMedia Layer) を利用して受信映像を表示するサンプルです。
SDL に GitHub or 公式サイトのリンクがあると親切そう

2022-07-21 03:52 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +**ビルドに関する質問は受け付けていません**
Github Actions 見てね、という一言があった方がよさそう。

2022-07-21 03:53 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +[main ブランチ](https://github.com/shiguredo/sora-cpp-sdk-samples/tree/main) をダウンロード、もしくはクローンして利用してください。
git clone で main ブランチを clone する例を載せておくと良さそう。

2022-07-21 03:53 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +multistrap に insecure なリポジトリからの取得を許可する設定をします
ここはこのドキュメントのスタンスが大事な部分だと考えます。
書くなら書くだし、書かないなら書かない。
現状だと中途半端にコマンドが載ってるので混乱しそうです。

なので `build.yml` を確認すると頭で謳って、ビルドコマンドと注意書きだけでよいのではないでしょうか？

2022-07-21 03:53 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +#### Windows 向けのビルドをする
Windows x86_64

2022-07-21 03:55 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +
これは指摘ミスですね。失礼しました。

2022-07-21 06:17 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +multistrap に insecure なリポジトリからの取得を許可する設定をします
以下の対応を行いました

- コマンド例の削除
- insecure なリポジトリからの取得を許可する設定を行う旨を multistrap の説明として追記
- ビルド全体の説明に Github Actions を確認してもらう旨を追記

2022-07-21 06:18 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 20.04 向けのビルドをする
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で x86_64 である旨を追記しました

2022-07-21 06:18 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +#### Mac 向けのビルドをする
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で指摘のとおり修正しました

2022-07-21 06:18 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 22.04 向けのビルドをする
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で x86_64 である旨を追記しました

2022-07-21 06:22 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +#### Ubuntu 20.04 で Ubuntu 20.04 (armv8) Jetson 向けのビルドをする
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で x86_64 である旨を追記しました

2022-07-21 06:22 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +以下は Sora サーバのシグナリング URL `wss://sora.example.com` の `sora` チャンネルに `sendrecv` で接続する例です。
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で修正しました。記載誤りでした。

2022-07-21 06:26 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +```
Windows のコマンドは ```powershell として > 始まりにしました
Linux のコマンドは ```shell として $ 始まりにしました

クリップボードにコピーした時に $ がついてくると面倒かなと思っているのでいい方法があるとよいのですが...

2022-07-21 06:26 UTC, miosakuma commented on README.md
> +- Ubuntu 22.04 x86_64 以降
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で対応しました。ありがとうございます。

2022-07-21 06:26 UTC, miosakuma commented on README.md
> +- macOS 12.4 M1 以降
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で arm64 で対応しました

2022-07-21 06:27 UTC, miosakuma commented on README.md
> +- Ubuntu 20.04 x86_64 以降
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で対応しました

2022-07-21 06:27 UTC, miosakuma commented on README.md
> +Sora と映像の送受信を行い、SDL (Simple DirectMedia Layer) を利用して受信映像を表示するサンプルです。
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で公式サイトにリンクしました。

2022-07-21 06:27 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +**ビルドに関する質問は受け付けていません**
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で Github Actions を見てもらうようにしました。

2022-07-21 06:29 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +[main ブランチ](https://github.com/shiguredo/sora-cpp-sdk-samples/tree/main) をダウンロード、もしくはクローンして利用してください。
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で追加しました

2022-07-21 06:30 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +#### Windows 向けのビルドをする
8b0c74b3dcd03e99f9488aff4e07ff77997e7155 で x86_64 を追加しました

2022-07-21 07:36 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +環境により必要なパッケージをインストールするようにしてください。
後からすいません。
「環境により」はすべてにおいてそうだと思うのでこの文言は不要だと思います。

2022-07-21 09:20 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +環境により必要なパッケージをインストールするようにしてください。
下記以外にも必要なパッケージを要求されたら入れるようにしてください、という意図でした。私の場合は libx11 関連のインストールも必要となったためです。ビルドエラーはメッセージを見て個別に対処してもらえると思うので削ろうと思います。

2022-07-21 11:51 UTC, torikizi approved these changes

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +以降のコマンドはダウンロードしたディレクトリのトップにいることを前提とします。
ダウンロードよりクローンって書いたほうが混乱しなさそう。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +コマンドラインでクローンした場合は以下のコマンドでダウンロードしたディレクトリのトップに移動します。
コマンドラインでクローンする例を載せてるのに、「コマンドラインでクローンした場合は」って書いてるのが違和感あります。それ以外の方法が普通でコマンドラインでクローンするのは特殊な方法、みたいな風に読めます。

あと cd コマンドの説明までいるかな…。クローンするコマンドの直後にしれっと書いてても普通に読めそうな気はします。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +  - C++ をビルドするためのコンポーネントを入れてください。CMake を利用します。
C++ コンポーネントは必要ですが、CMake は run.py 実行時にダウンロードしてきてるはずなので、無くても大丈夫なはず。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +```
↑のやつを反映したら、もうこのコマンドは不要そう。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +成功した場合、以下のファイルが作成されます。`.¥_build¥windows_x86_64¥release¥sdl_sample¥Release` に `sdl_sample.exe` が作成されます。
なんか「作成されます」が２個連続してて気になるので「成功した場合、`.¥_build¥windows_x86_64¥release¥sdl_sample¥Release` に `sdl_sample.exe` が作成されます。」でいいような気が。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +- Python 3
libdrm-dev と pkg-config が Ubuntu のパッケージ名なのに、Python 3 だけ違うのが気になります。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +> python .¥sdl_sample¥windows_x86_64¥run.py
macOS や Ubuntu では python3 なのに、こっちでは python コマンドなのが気になりました。
あと最初の `.\` は macOS や Ubuntu でのビルドでは入ってないので無い方が統一感あるかも。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +  - insecure なリポジトリからの取得を許可する設定を行う
これがさっと分かる人はほぼ居ないと思うので、「詳細は build.yml を参照してください」みたいな感じで build.yml へのリンクを再度張ってあげても良さそう。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +$ ./sdl_sample  --signaling-url wss://sora.example.com/signaling --role sendrecv --channel-id sora --multistream true
`./sdl_sample` と `--signaling-url` の間に空白２つあるのが気になります。

2022-07-21 14:25 UTC, melpon commented on doc/USE_SDL_SAMPLE.md
> +    - VP8 / VP9 / AV1 / H264 が指定可能ですが利用可能なコーデックはプラットフォームに依存します
未指定だったらどうなるかも書いておいた方が親切そう。
たしか Sora の設定を使うはずなんだけど、sora.conf のドキュメント見ても未指定の場合のコーデックを変更する設定が無さそうに見える…

2022-07-21 14:33 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +    - VP8 / VP9 / AV1 / H264 が指定可能ですが利用可能なコーデックはプラットフォームに依存します
未指定のときに VP9 が設定されることについてはシグナリングの方で記載があって、conf で設定はできなかったと認識しています
https://sora-doc.shiguredo.jp/SIGNALING#d47f4d

2022-07-22 01:49 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +Sora と映像の送受信を行い、SDL (Simple DirectMedia Layer) を利用して映像を表示するサンプルです。
SDL にリンク

2022-07-22 01:50 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +このサンプルに Sora Labo / Tobi に接続する機能を用意する予定は現在ありません。独自に実装していただく必要があります。
Sora Labo / Tobi にリンク

2022-07-22 01:50 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +コマンドラインでクローンした場合は以下のコマンドでダウンロードしたディレクトリのトップに移動します。
cd はいらないとおもう。clone 前提で書くに +1

2022-07-22 01:51 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +- Python 3
Python3 のバージョン確認したほうがいい cc: @melpon

2022-07-22 01:52 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +$ python3 sdl_sample/macos_arm64/run.py
Python のバージョン確認はあったほうがいいです（一応。 @torikizi や @miosakuma が使ってるバージョンでいいとおもいます。

2022-07-22 01:52 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/macos_arm64/release/sdl_sample/sdl_sample
tree とかで結果見せた方がいいと思う。

2022-07-22 01:53 UTC, voluntas approved these changes

2022-07-22 01:53 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +- Python 3
Ubuntu デフォルトの Python であれば python3 みたいに書いた方がいいのと、 Ubuntu であれば apt 以外使うことはないので apt で書いちゃっていいと思いますよ。

2022-07-22 01:53 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/ubuntu-20.04_x86_64/release/sdl_sample/sdl_sample
tree がよいかと。結果が見えた方がいいでしょう。

2022-07-22 01:53 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +- Python 3
ここも apt 化して良いと思う

2022-07-22 01:54 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/ubuntu-22.04_x86_64/release/sdl_sample/sdl_sample
tree でいい。

2022-07-22 01:54 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +NVIDIA Jetson 上ではビルドできません。Ubuntu 20.04 x86_64 上でクロスコンパイルしたバイナリを利用するようにしてください。
強調構文にしておいたほうがいい。

2022-07-22 01:54 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/ubuntu-20.04_armv8_jetson/release/sdl_sample/sdl_sample
tree

2022-07-22 01:55 UTC, voluntas requested changes

2022-07-22 01:55 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +    - VP8 / VP9 / AV1 / H264 が指定可能ですが利用可能なコーデックはプラットフォームに依存します
未指定の場合は Sora のデフォルトである VP9 が利用されますでいいとおもう。

2022-07-22 01:58 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +$ python3 sdl_sample/macos_arm64/run.py
自分は以下の環境でやっています。
Windows ：Python 3.10.4
Mac：Python 3.8.10
Ubuntu：Python 3.8.10

2022-07-22 05:28 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +コマンドラインでクローンした場合は以下のコマンドでダウンロードしたディレクトリのトップに移動します。
クローン前提で書いてダウンロードの記載は消します。
cd コマンドはクローンコマンドの下に書いておこうと思います。

2022-07-22 05:37 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +Sora と映像の送受信を行い、SDL (Simple DirectMedia Layer) を利用して映像を表示するサンプルです。
Sora にもリンクを追加します

2022-07-22 05:43 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +- Python 3
Python3 の最新版を入れてビルド＋動作確認をしようと思います。

2022-07-22 06:33 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +- Python 3
Python 3 もパッケージ名で書くようにして、 apt コマンドを追記するようにします。
人によってすでにインストール済みのものもあると思うので 1 行ずつ 3 行で書きます。

2022-07-22 07:35 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/macos_arm64/release/sdl_sample/sdl_sample
量が多くなりすぎないように sdl_sample が存在するディレクトリ、`_build/macos_arm64/release/sdl_sample` の tree を出すようにします

2022-07-22 08:04 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +> python .¥sdl_sample¥windows_x86_64¥run.py
自分の環境が python.exe でインストールされたのでそうしていたのですが、Windows のアプリストアからインストールした場合は python3.exe が入りました。python3 にします。

2022-07-22 08:07 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +  - insecure なリポジトリからの取得を許可する設定を行う
apt コマンドを追記することにしたのでコマンドもあわせて書くようにします

2022-07-22 09:05 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +以降のコマンドはダウンロードしたディレクトリのトップにいることを前提とします。
d569d3230b642e9a46128140306927b4dd597dfb にてクローンを前提の記載にしました。

2022-07-22 09:05 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +コマンドラインでクローンした場合は以下のコマンドでダウンロードしたディレクトリのトップに移動します。
ダウンロードの文言は消して、cd はコマンド git clone コマンドに入れました。d569d3230b642e9a46128140306927b4dd597dfb で対応しています。

2022-07-22 09:08 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +  - C++ をビルドするためのコンポーネントを入れてください。CMake を利用します。
d569d3230b642e9a46128140306927b4dd597dfb で CMake についての記載を削除しました。

2022-07-22 09:09 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +```
はい、tree の結果に変更になりました。

2022-07-22 09:46 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +$ python3 sdl_sample/macos_arm64/run.py
d569d3230b642e9a46128140306927b4dd597dfb で事前準備として Python のバージョンを入れました

2022-07-22 09:47 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/macos_arm64/release/sdl_sample/sdl_sample
c3c71be99cb66f01c3841c9accfaf0bfc9f768e8 で tree の結果に変更しました

2022-07-22 09:47 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/ubuntu-20.04_x86_64/release/sdl_sample/sdl_sample
c3c71be で tree の結果に変更しました

2022-07-22 09:48 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +- Python 3
apt コマンドを追記しました

2022-07-22 09:48 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/ubuntu-22.04_x86_64/release/sdl_sample/sdl_sample
c3c71be で tree の結果に変更しました

2022-07-22 09:48 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +NVIDIA Jetson 上ではビルドできません。Ubuntu 20.04 x86_64 上でクロスコンパイルしたバイナリを利用するようにしてください。
d569d3230b642e9a46128140306927b4dd597dfb で強調表示に変更しました。

2022-07-22 09:49 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +$ ls -l _build/ubuntu-20.04_armv8_jetson/release/sdl_sample/sdl_sample
c3c71be で tree の結果に変更しました

2022-07-22 09:50 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +    - VP8 / VP9 / AV1 / H264 が指定可能ですが利用可能なコーデックはプラットフォームに依存します
d569d3230b642e9a46128140306927b4dd597dfb で「未指定の場合は Sora のデフォルトである VP9 が利用されます」の記載を追記しました

2022-07-22 10:12 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +multistrap に insecure なリポジトリからの取得を許可する設定をします
@torikizi apt コマンドを書くことになったので、こちらのコマンドも復活させます。
当初の状態に戻すつもりですが、違和感があった場合はコメントをお願いします。

2022-07-22 10:18 UTC, miosakuma commented
レビューありがとうございました。一通り対応しましたが、気になる箇所あれば引き続きコメントをお願いします。

2022-07-22 10:21 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +multistrap に insecure なリポジトリからの取得を許可する設定をします
書く方に寄せたということと認識しました。違和感ありません。

2022-07-22 10:30 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +- python3
細かいのですが、インストールコマンドを入れるならこのラインナップの記載はなくても良い気がします。

2022-07-22 10:46 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +- python3
ありがとうございます。削除しました。

2022-07-25 07:57 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +[Sora](https://sora.shiguredo.jp/) と映像の送受信を行い、[SDL (Simple DirectMedia Layer)](https://www.libsdl.org/) を利用して映像を表示するサンプルです。
SDL って音声は送受信しないんでしたっけ？（念のための確認）

2022-07-25 07:58 UTC, voluntas approved these changes

2022-07-25 08:05 UTC, torikizi commented on doc/USE_SDL_SAMPLE.md
> +[Sora](https://sora.shiguredo.jp/) と映像の送受信を行い、[SDL (Simple DirectMedia Layer)](https://www.libsdl.org/) を利用して映像を表示するサンプルです。
いえ、音声も送受信します。

2022-07-25 08:17 UTC, voluntas commented on doc/USE_SDL_SAMPLE.md
> +[Sora](https://sora.shiguredo.jp/) と映像の送受信を行い、[SDL (Simple DirectMedia Layer)](https://www.libsdl.org/) を利用して映像を表示するサンプルです。
でれば、音声と映像の送受信にするのが正しそう。 @miosakuma

2022-07-25 08:52 UTC, miosakuma commented on doc/USE_SDL_SAMPLE.md
> +[Sora](https://sora.shiguredo.jp/) と映像の送受信を行い、[SDL (Simple DirectMedia Layer)](https://www.libsdl.org/) を利用して映像を表示するサンプルです。
ありがとうございます、対応しました。

2022-07-25 13:36 UTC, voluntas approved these changes

2022-07-25 17:06 UTC, melpon approved these changes

2022-07-26 06:35 UTC, miosakuma commented
レビューありがとうございました。マージします。

2022-07-26 06:35 UTC, merged